order.name=Order Service
order.timeout=5000
order.owner=Order Default

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=health,info,refresh,busrefresh


message=This is order-service default
custom.refresh=this is refreshing message from order default